import fs from 'fs'
import path from 'path'
import os from 'os'

const HOOKS_SERVER_PORT = 27182
const HOOK_SCRIPT_NAME = 'claudia-bridge.sh'

function getClaudeSettingsPath(): string {
  return path.join(os.homedir(), '.claude', 'settings.json')
}

function getHookScriptPath(): string {
  return path.join(os.homedir(), '.claude', HOOK_SCRIPT_NAME)
}

function readClaudeSettings(): Record<string, unknown> {
  const settingsPath = getClaudeSettingsPath()
  if (!fs.existsSync(settingsPath)) return {}
  try {
    return JSON.parse(fs.readFileSync(settingsPath, 'utf-8'))
  } catch {
    return {}
  }
}

function writeClaudeSettings(settings: Record<string, unknown>): void {
  const settingsPath = getClaudeSettingsPath()
  const dir = path.dirname(settingsPath)
  if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true })
  fs.writeFileSync(settingsPath, JSON.stringify(settings, null, 2), 'utf-8')
}

function createHookScript(): void {
  const scriptPath = getHookScriptPath()
  const script = `#!/bin/bash
# Claudia Bridge Hook - sends Claude Code events to Claudia app
# Auto-generated by Claudia - do not edit manually

PAYLOAD=$(cat)

# Inject cwd from the hook's working directory so the app can match sessions.
# Uses sed to add "cwd" before the closing brace if not already present.
CWD_ESCAPED=$(pwd | sed 's/\\\\/\\\\\\\\/g; s/"/\\\\"/g')
if ! echo "$PAYLOAD" | grep -q '"cwd"'; then
  PAYLOAD=$(echo "$PAYLOAD" | sed "s|}$|, \\"cwd\\": \\"$CWD_ESCAPED\\"}|")
fi

curl -s -X POST http://127.0.0.1:${HOOKS_SERVER_PORT} \\
  -H "Content-Type: application/json" \\
  -d "$PAYLOAD" > /dev/null 2>&1 || true

exit 0
`
  fs.writeFileSync(scriptPath, script, { encoding: 'utf-8', mode: 0o755 })
}

const HOOK_EVENTS = ['SessionStart', 'Stop', 'SessionEnd', 'Notification', 'PostToolUse', 'UserPromptSubmit']

export function installHooks(): { success: boolean; error?: string } {
  try {
    createHookScript()
    const scriptPath = getHookScriptPath()
    const settings = readClaudeSettings()

    if (!settings.hooks) settings.hooks = {}
    const hooks = settings.hooks as Record<string, unknown[]>

    for (const event of HOOK_EVENTS) {
      if (!hooks[event]) hooks[event] = []
      const existing = hooks[event] as Array<Record<string, unknown>>

      const alreadyInstalled = existing.some(
        h =>
          (typeof h.command === 'string' && h.command.includes('claudia-bridge')) ||
          (Array.isArray(h.hooks) &&
            (h.hooks as Array<Record<string, unknown>>).some(
              hh => typeof hh.command === 'string' && hh.command.includes('claudia-bridge')
            ))
      )
      if (alreadyInstalled) continue

      existing.push({
        hooks: [
          {
            type: 'command',
            command: scriptPath,
            timeout: 5
          }
        ]
      })
    }

    settings.hooks = hooks
    writeClaudeSettings(settings)

    return { success: true }
  } catch (err) {
    return { success: false, error: String(err) }
  }
}

export function uninstallHooks(): { success: boolean; error?: string } {
  try {
    const settings = readClaudeSettings()
    if (!settings.hooks) return { success: true }

    const hooks = settings.hooks as Record<string, unknown[]>
    for (const event of Object.keys(hooks)) {
      hooks[event] = (hooks[event] as Array<Record<string, unknown>>).filter(
        h =>
          !(typeof h.command === 'string' && h.command.includes('claudia-bridge')) &&
          !(
            Array.isArray(h.hooks) &&
            (h.hooks as Array<Record<string, unknown>>).some(
              hh => typeof hh.command === 'string' && hh.command.includes('claudia-bridge')
            )
          )
      )
      if (hooks[event].length === 0) delete hooks[event]
    }

    if (Object.keys(hooks).length === 0) delete settings.hooks

    writeClaudeSettings(settings)

    const scriptPath = getHookScriptPath()
    if (fs.existsSync(scriptPath)) fs.unlinkSync(scriptPath)

    return { success: true }
  } catch (err) {
    return { success: false, error: String(err) }
  }
}

export function areHooksInstalled(): boolean {
  try {
    const settings = readClaudeSettings()
    if (!settings.hooks) return false
    const hooks = settings.hooks as Record<string, unknown[]>
    const sessionStartHooks = hooks['SessionStart'] as Array<Record<string, unknown>> | undefined
    if (!sessionStartHooks) return false
    return sessionStartHooks.some(
      h =>
        (typeof h.command === 'string' && h.command.includes('claudia-bridge')) ||
        (Array.isArray(h.hooks) &&
          (h.hooks as Array<Record<string, unknown>>).some(
            hh => typeof hh.command === 'string' && hh.command.includes('claudia-bridge')
          ))
    )
  } catch {
    return false
  }
}
